train:
  #  定义网络与网络参数
  gan_type:
  G_net:
    network: N
    net_param:
      in_dim: 0
      out_dim: 0
    Loss_fn:
      - name: L1loss
        weight: 1
      - name: L2loss
        weight: 1
    optimizer:
      Adam
    optimizer_params:
      - lr: 0.001
      - weight_decay: 0

    lr_scheduler:
      name: MultiStepLR
      param:
        milestones: 5
        gamma: 0.1
        last_epoch: -1

  D_net:
    network: N
    net_param:
      in_dim: 0
      out_dim: 0
    Loss_fn:
      - name: L1loss
        weight: 1
      - name: L2loss
        weight: 1
    optimizer:
      AdamW
    lr: 0.001

    lr_scheduler:
      - name: MultiStepLR
      - param:
          milestones: 5
          gamma: 0.1
          last_epoch: -1


save:
  save_dir:
    'result'
  save_epoch:
    1
  save_best:
    True
  pretrained_g_optimizer_and_schedule_path:
    None
  pretrained_d_optimizer_and_schedule_path:
    None
  pretrained_g_net_path:
    None
  pretrained_d_net_path:
    None
  pretrained_e_net_path:
    None


