train:
  #  定义网络与网络参数
  gan_type:
  lr_update_per_step: False
  version: '001'
  gpu_ids: [0]

  E_decay: 0

  dist: False
  find_unused_parameters: False
  _set_static_graph: False

  G_net:
    network: resnet
    net_param:
      in_dim: 0
      out_dim: 0
    Loss_fn:
      loss: 
      - L1loss 
      - MSELoss
      weight: 
      - 1
      - 1
    optimizer:
      name: Adam
      param:
        lr: 0.001
        weight_decay: 0

    lr_scheduler:
      name: MultiStepLR
      param:
        milestones: 5
        gamma: 0.1
        last_epoch: -1

  D_net:
    network: N
    net_param:
      in_dim: 0
      out_dim: 0
    Loss_fn:
      - name: L1loss
        weight: 1
      - name: L2loss
        weight: 1
    optimizer: AdamW
    lr: 0.001

    lr_scheduler:
      - name: MultiStepLR
      - param:
          milestones: 5
          gamma: 0.1
          last_epoch: -1

save:
  resume: True
  dir: "result"
  epoch: 1
  best: True
  net_load_strict: True
  pretrained: False
  pretrain_path:
    G_orthers_path: None
    D_orthers_path: None
    G_net_path: None
    D_net_path: None
    E_net_path: None
