train:
  #  定义网络与网络参数
  seed: 42
  gan_type:
  lr_update_per_step: False
  version: "001"
  gpu_ids: [ 0 ]
  ncols: 80
  E_decay: 0
  num_epoch: 1
  dist: False
  find_unused_parameters: False
  _set_static_graph: False # 使用静态图

  Metric:
    - PSNR
    - NMSE


  G_net:
    network_dir: models.model
    network: hfs
    net_param:
      in_dim: 0
      out_dim: 0
    Loss_fn:
      loss:
        - L1loss
        - MSELoss
      weight:
        - 1
        - 1
    optimizer:
      name: Adam
      param:
        lr: 0.001
        weight_decay: 0
    optimizer_clipgrad: False
    lr_scheduler:
      name: MultiStepLR
      param:
        milestones: [ 100, 2000, 3000 ]
        gamma: 0.1
        last_epoch: -1

  D_net:
    network_dir: models.model
    network: DISnet
    net_param:
      in_dim: 0
      out_dim: 0
    Loss_fn:
      loss:
        - L1loss
        - MSELoss
      weight:
        - 1
        - 1
    optimizer:
      name: Adam
      param:
        lr: 0.001
        weight_decay: 0

    lr_scheduler:
      name: MultiStepLR
      param:
        milestones: [ 100, 2000, 3000 ]
        gamma: 0.1
        last_epoch: -1

diffusion:
  num_timesteps: 4
  use_geometric: True
  beta_min: 0.02
  beta_max: 0.08
  lazy_reg_step: 15
  r1_gamma: 0.02
  nz: 100
  rec_loss: True



data:
  prefetch_generator: True
  data_path: D:/dataset/mini_test
  trainset_path: training_mini.pickle
  testset_path: testing_mini.pickle
  validset_path: validation_mini.pickle

  data_loader_param:
    batch_size: 1
    shuffle: True
    num_workers: 4
    drop_last: True
    pin_memory: True

  to_bad_fn_param:
    mask_path: data/mask
    mask_type: gaussian1d
    mask_level: 30

save:
  On_tensorboard: True
  resume: True
  resume_lable: best
  dir: "result"
  epoch: 1
  best: True
  net_load_strict: True
  pretrain_path: None
